@extends('structure.master')
@section('content')
    {{-- Search Section --}}
    <div class="row">
        <div class="col-lg-12">
            <div class="card border-0 shadow-sm rounded">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i data-feather="dollar-sign" class="me-2"></i>Search Bonus Process Batch
                    </h5>
                </div>
                <div class="card-header border-bottom p-4">
                    <div class="row align-items-start">
                        {{-- Filter Section --}}
                        <div class="col-md-12">
                            <div class="border rounded shadow-sm p-3 filter-section-bg">
                                <form id="filterForm">
                                    {{-- Keyword Search --}}
                                    <div class="row mb-2">
                                        <div class="col-12">
                                            <label for="keywordSearch" class="form-label text-muted small fw-semibold mb-1">
                                                Keyword Search
                                            </label>
                                            <div class="input-group input-group-md">
                                                <input type="text" class="form-control border-end-0" id="keywordSearch"
                                                    name="keyword"
                                                    placeholder="Search by batch ID, salary month, approval status..."
                                                    aria-label="Keyword Search" value="{{ request('keyword') }}">
                                                <span class="input-group-text border-start-0 input-group-bg">
                                                    <i class="mdi mdi-magnify text-muted"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    {{-- Reset Button --}}
                                    <div class="row">
                                        <div class="col-12 text-end">
                                            <button type="button" id="resetFilters"
                                                class="btn btn-outline-secondary btn-sm">
                                                <i class="mdi mdi-refresh"></i> Reset
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {{-- List Section --}}
        <div class="col-lg-12 mt-3">
            <div class="card border-0 shadow-sm rounded">
                <div class="card-header">
                    <h5 class="card-title mb-0">Bonus Process List</h5>
                </div>
                <div class="card-body">
                    {{-- Action Buttons --}}
                    <div class="d-flex justify-content-between mb-3">
                        <a type="button" class="btn btn-warning btn-sm" href="{{route('bonus.create')}}">
                            <i style="height: 12px; width: 12px" data-feather="plus"></i> Create
                        </a>
                    </div>

                    <div class="table-responsive" id="search-result">
                        <table class="table table-bordered table-hover mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Batch ID</th>
                                    <th>Salary Month</th>
                                    <th class="text-center">Approval Status</th>
                                    <th>Generated By</th>
                                    <th class="text-center" style="width: 100px;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            @php
                                $sl = \App\HelperClass::indexNumberSerialization($payrollProcesses);
                            @endphp
                                @forelse($payrollProcesses as $item)
                                    <tr>
                                        <th scope="row" class="text-center">{{ $sl++ }}</th>
                                        <td>
                                            <strong class="text-primary">{{ $item->batch_id }}</strong>
                                        </td>
                                        <td>
                                            <i data-feather="calendar" class="text-muted"
                                                style="width: 14px; height: 14px;"></i>
                                            {{ \Carbon\Carbon::parse($item->salary_month)->format('F Y') }}
                                        </td>
                                        <td class="text-center">
                                            @if ($item->approval_status == 'Approved')
                                                <span class="badge text-bg-success">Approved</span>
                                            @elseif($item->approval_status == 'Pending')
                                                <span class="badge text-bg-warning">Pending</span>
                                            @elseif($item->approval_status == 'Rejected')
                                                <span class="badge text-bg-danger">Rejected</span>
                                            @else
                                                <span class="badge text-bg-secondary">{{ $item->approval_status }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <div class="avatar-circle me-2">
                                                    {{ strtoupper(substr($item->generated_by, 0, 2)) }}
                                                </div>
                                                <div>
                                                    <strong>{{ $item->generated_by ?? 'N/A'}}</strong>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="text-center" style="width: 200px" >
                                            <button type="button" class="btn btn-info btn-sm view-details"
                                                data-id="{{ $item->id }}"
                                                data-batch-id="{{ $item->batch_id }}"
                                                data-salary-month="{{ \Carbon\Carbon::parse($item->salary_month)->format('F Y') }}"
                                                data-approval-status="{{ $item->approval_status }}"
                                                data-generated-by="{{ $item->generated_by ?? 'N/A' }}"
                                                data-company="{{ $item->getCompany->name ?? 'N/A' }}"
                                                data-branch="{{ $item->getBranch->name ?? 'N/A' }}"
                                                data-division="{{ $item->getDivision->name ?? 'N/A' }}"
                                                data-department="{{ $item->getDepartment->name ?? 'N/A' }}"
                                                data-section="{{ $item->getSection->name ?? 'N/A' }}"
                                                data-type="{{ $item->type }}"
                                                data-approved-by="{{ $item->approved_by ?? 'N/A' }}"
                                                data-total-amount="{{ number_format($item->total_amount, 2) }}"
                                                data-total-employee="{{ $item->total_employee }}"
                                                data-created-at="{{ \Carbon\Carbon::parse($item->created_at)->format('d M, Y H:i A') }}"
                                                title="View Details">
                                                <i style="height: 12px; width: 12px" data-feather="eye"></i>
                                            </button>

                                            @if ($item->approval_status == 'pending')
                                                {{-- Edit Button --}}
                                                <a href="{{ route('bonus.edit', $item->id) }}"
                                                   class="btn btn-primary btn-sm" title="Edit">
                                                    <i style="height: 12px; width: 12px" data-feather="edit"></i>
                                                </a>

                                                {{-- Approve Button --}}
                                                <form class="d-inline"
                                                      action="{{ route('bonus.status.update', $item->id) }}"
                                                      method="POST">
                                                    @csrf
                                                    @method('PUT')
                                                    <input type="hidden" name="status" value="approved">

                                                    <button type="submit" class="btn btn-success btn-sm confirmApprove"
                                                            title="Approve">
                                                        <i style="height: 12px; width: 12px" data-feather="check"></i>
                                                    </button>
                                                </form>

                                                {{-- Reject Button --}}
                                                <form class="d-inline" method="POST"
                                                      action="{{ route('bonus.status.update', $item->id) }}">
                                                    @csrf
                                                    @method('PUT')
                                                    <input type="hidden" name="status" value="rejected">
                                                    <button type="submit" class="btn btn-danger btn-sm confirmReject"
                                                            title="Reject">
                                                        <i style="height: 12px; width: 12px" data-feather="x"></i>
                                                    </button>
                                                </form>
                                            @endif
                                            <form class="d-inline"
                                                  action="{{ route('bonus.delete', $item->id) }}"
                                                  method="POST">
                                                @csrf
                                                @method('delete')
                                                <button type="submit" class="btn btn-danger btn-sm confirmDelete"
                                                        title="Delete">
                                                    <i style="height: 12px; width: 12px" data-feather="trash"></i>
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="text-center py-4">
                                            <div class="text-muted">
                                                <i data-feather="inbox" style="width: 48px; height: 48px;"></i>
                                                <p class="mt-2 mb-0">No payroll processes found</p>
                                            </div>
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    <div class="mt-2">
                        {{ $payrollProcesses->links() }}
                    </div>

                </div>
            </div>
        </div>
    </div>

    {{-- Include Modal --}}
    @include('payroll.bonus.partials.view')

    <style>
        .avatar-circle {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 14px;
        }

        .filter-section-bg {
            background-color: #f8f9fa;
        }

        .input-group-bg {
            background-color: #fff;
        }

        .modal-body label.text-muted {
            font-size: 0.875rem;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 0.25rem;
        }
    </style>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function() {
            // Initialize Feather icons
            if (typeof feather !== 'undefined') {
                feather.replace();
            }

            /* ================= VIEW DETAILS CLICK ================= */

            $('.view-details').on('click', function() {

                const payrollId = $(this).data('id'); // ✅ REQUIRED

                const batchId = $(this).data('batch-id');
                const salaryMonth = $(this).data('salary-month');
                const approvalStatus = $(this).data('approval-status');
                const generatedBy = $(this).data('generated-by');
                const company = $(this).data('company');
                const branch = $(this).data('branch');
                const division = $(this).data('division');
                const department = $(this).data('department');
                const section = $(this).data('section');
                const type = $(this).data('type');
                const status = $(this).data('status');
                const approvedBy = $(this).data('approved-by');
                const totalAmount = $(this).data('total-amount');
                const totalEmployee = $(this).data('total-employee');
                const createdAt = $(this).data('created-at');

                /* ================= SET MODAL DATA ================= */

                $('#modal-batch-id').text(batchId);
                $('#modal-salary-month').text(salaryMonth);
                $('#modal-type').text(type);
                $('#modal-status').html('<span class="badge text-bg-info">' + status + '</span>');
                $('#modal-company').text(company);
                $('#modal-branch').text(branch);
                $('#modal-division').text(division);
                $('#modal-department').text(department);
                $('#modal-section').text(section);
                $('#modal-generated-by').text(generatedBy);
                $('#modal-approved-by').text(approvedBy);
                $('#modal-total-amount').text('৳ ' + totalAmount);
                $('#modal-total-employee').text(totalEmployee);
                $('#modal-created-at').text(createdAt);

                /* ================= APPROVAL BADGE ================= */

                let approvalBadge = '';
                if (approvalStatus === 'Approved') {
                    approvalBadge = '<span class="badge text-bg-success">Approved</span>';
                } else if (approvalStatus === 'Pending') {
                    approvalBadge = '<span class="badge text-bg-warning">Pending</span>';
                } else if (approvalStatus === 'Rejected') {
                    approvalBadge = '<span class="badge text-bg-danger">Rejected</span>';
                } else {
                    approvalBadge = '<span class="badge text-bg-secondary">' + approvalStatus + '</span>';
                }
                $('#modal-approval-status').html(approvalBadge);

                /* ================= SET VIEW ELIGIBLE BUTTON ================= */

                const viewUrl = "{{ route('bonus.show', ':id') }}".replace(':id', payrollId);
                $('#view-eligible-btn').attr('href', viewUrl);

                /* ================= SHOW MODAL ================= */

                const modal = new bootstrap.Modal(document.getElementById('viewDetailsModal'));
                modal.show();

                setTimeout(function() {
                    if (typeof feather !== 'undefined') {
                        feather.replace();
                    }
                }, 100);
            });

            /* ================= AJAX SUPPORT ================= */

            function bindViewDetailsHandlers() {
                $('.view-details').off('click').on('click', function() {

                    const payrollId = $(this).data('id'); // ✅ REQUIRED

                    const batchId = $(this).data('batch-id');
                    const salaryMonth = $(this).data('salary-month');
                    const approvalStatus = $(this).data('approval-status');
                    const generatedBy = $(this).data('generated-by');
                    const company = $(this).data('company');
                    const branch = $(this).data('branch');
                    const division = $(this).data('division');
                    const department = $(this).data('department');
                    const section = $(this).data('section');
                    const type = $(this).data('type');
                    const approvedBy = $(this).data('approved-by');
                    const totalAmount = $(this).data('total-amount');
                    const totalEmployee = $(this).data('total-employee');
                    const createdAt = $(this).data('created-at');

                    $('#modal-batch-id').text(batchId);
                    $('#modal-salary-month').text(salaryMonth);
                    $('#modal-type').text(type);
                    $('#modal-company').text(company);
                    $('#modal-branch').text(branch);
                    $('#modal-division').text(division);
                    $('#modal-department').text(department);
                    $('#modal-section').text(section);
                    $('#modal-generated-by').text(generatedBy);
                    $('#modal-approved-by').text(approvedBy);
                    $('#modal-total-amount').text('৳ ' + totalAmount);
                    $('#modal-total-employee').text(totalEmployee);
                    $('#modal-created-at').text(createdAt);

                    let approvalBadge = '';
                    if (approvalStatus === 'Approved') {
                        approvalBadge = '<span class="badge text-bg-success">Approved</span>';
                    } else if (approvalStatus === 'Pending') {
                        approvalBadge = '<span class="badge text-bg-warning">Pending</span>';
                    } else if (approvalStatus === 'Rejected') {
                        approvalBadge = '<span class="badge text-bg-danger">Rejected</span>';
                    } else {
                        approvalBadge = '<span class="badge text-bg-secondary">' + approvalStatus + '</span>';
                    }
                    $('#modal-approval-status').html(approvalBadge);

                    /* ================= SET VIEW ELIGIBLE BUTTON ================= */

                    const viewUrl = "{{ route('bonus.show', ':id') }}".replace(':id', payrollId);
                    $('#view-eligible-btn').attr('href', viewUrl);

                    const modal = new bootstrap.Modal(document.getElementById('viewDetailsModal'));
                    modal.show();

                    setTimeout(function() {
                        if (typeof feather !== 'undefined') {
                            feather.replace();
                        }
                    }, 100);
                });
            }

        });
    </script>
@endsection
