<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eligible Employees for Bonus Batch - Print</title>
    <style>
        @page {
            size: A4 portrait;
            margin: 15mm 10mm;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: Arial, sans-serif;
            font-size: 9pt;
            line-height: 1.3;
            color: #000;
            background: #fff;
        }

        .report-header {
            border-bottom: 3px solid #333;
            margin-bottom: 15px;
            padding-bottom: 10px;
        }

        .report-header h1 {
            font-size: 16pt;
            font-weight: bold;
            margin-bottom: 4px;
        }

        .report-header p {
            font-size: 8pt;
            color: #666;
            margin-bottom: 2px;
        }

        .report-info {
            display: flex;
            justify-content: space-between;
            margin-bottom: 12px;
            padding: 6px 8px;
            background: #f5f5f5;
            border: 1px solid #ccc;
            font-size: 8pt;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
        }

        thead {
            background-color: #ddd;
            border-bottom: 2px solid #333;
        }

        th {
            padding: 6px 4px;
            font-weight: bold;
            text-align: center;
            border: 1px solid #999;
            font-size: 8pt;
        }

        td {
            padding: 5px 4px;
            border: 1px solid #ccc;
            font-size: 8pt;
            vertical-align: middle;
            text-align: center;
        }

        tbody tr {
            page-break-inside: avoid;
        }

        tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .text-left {
            text-align: left;
        }

        .report-footer {
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #ccc;
            font-size: 8pt;
            color: #666;
            display: flex;
            justify-content: space-between;
        }
    </style>
</head>

<body>

    <div class="report-header">
        <h1>Eligible Employees for Bonus & Reward</h1>
        <p><strong>Batch ID:</strong> {{ $process->batch_id }}</p>
        <p><strong>Salary Month:</strong> {{ $salary_month ? \Carbon\Carbon::parse($salary_month)->format('F Y') : '—' }}</p>
        <p><strong>Report Date:</strong> {{ date('l, F j, Y') }}</p>
    </div>

    <div class="report-info">
        <div><strong>Total Eligible Employees:</strong> {{ count($records) }}</div>
        <div><strong>Total Amount:</strong> ৳{{ number_format($process->total_amount ?? 0, 2) }}</div>
        <div><strong>Printed:</strong> {{ date('d M, Y h:i A') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width:5%;">#</th>
                <th style="width:35%;">Employee Name</th>
                <th style="width:20%;">Employee ID</th>
                <th style="width:20%;">System ID</th>
                <th style="width:20%;">Bonus Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($records as $index => $record)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td class="text-left">
                        <strong>{{ $record->getEmployee?->full_name ?? 'N/A' }}</strong>
                    </td>
                    <td>{{ $record->getEmployee?->applicant_id ?? 'N/A' }}</td>
                    <td>{{ $record->getEmployee?->system_id ?? 'N/A' }}</td>
                    <td>৳{{ number_format($record->amount ?? 0, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="report-footer">
        <div><strong>Generated by HRMS</strong></div>
        <div>Page 1 of 1</div>
    </div>

    <script>
        window.onload = function() {
            window.print();
        };
    </script>

</body>

</html>
