<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Announcement - {{ $announcement->title }}</title>
    <style>
        @page { margin: 20px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; color: #333; line-height: 1.5; margin: 0; padding: 15px; background-color: #fff; }
        .header-table { width: 100%; border-bottom: 2px solid #974063; margin-bottom: 15px; padding-bottom: 10px; }
        .company-name { font-size: 18px; font-weight: bold; color: #974063; margin: 0; }
        .company-details { font-size: 9px; color: #666; margin: 0; }
        .announcement-title { font-size: 16px; font-weight: bold; color: #974063; margin: 15px 0 5px 0; text-transform: uppercase; }
        .meta-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; background-color: #f9f9f9; border: 1px solid #eee; border-radius: 4px; }
        .meta-table td { padding: 6px 10px; border-bottom: 1px solid #eee; font-size: 9px; }
        .label { font-weight: bold; color: #974063; width: 25%; text-transform: uppercase; }
        .value { color: #333; width: 75%; }
        .content-section { font-size: 11px; color: #222; margin-top: 15px; line-height: 1.6; }
        .content-section p { margin-bottom: 10px; }
        .footer { margin-top: 40px; text-align: center; font-size: 8px; color: #999; border-top: 1px solid #eee; padding-top: 8px; }
    </style>
</head>
<body>
    <table class="header-table">
        <tr>
            <td>
                <h1 class="company-name">{{ $companyInfo->name }}</h1>
                @if($companyInfo->address)
                    <p class="company-details">{{ $companyInfo->address }}</p>
                @endif
                @if($companyInfo->phone || $companyInfo->email)
                    <p class="company-details">
                        @if($companyInfo->phone) Phone: {{ $companyInfo->phone }} @endif
                        @if($companyInfo->phone && $companyInfo->email) | @endif
                        @if($companyInfo->email) Email: {{ $companyInfo->email }} @endif
                    </p>
                @endif
            </td>
            <td style="text-align: right; vertical-align: middle;">
                <h2 style="margin: 0; color: #974063; font-size: 14px; font-weight: bold; letter-spacing: 1px;">OFFICIAL ANNOUNCEMENT</h2>
            </td>
        </tr>
    </table>

    <div class="announcement-title">{{ $announcement->title }}</div>

    <table class="meta-table">
        <tr>
            <td class="label">Date Posted</td>
            <td class="value">{{ $announcement->created_at->format('F d, Y h:i A') }}</td>
        </tr>
        @if($announcement->company)
            <tr>
                <td class="label">Company</td>
                <td class="value">{{ $announcement->company->name }}</td>
            </tr>
        @endif
        @if($announcement->branch)
            <tr>
                <td class="label">Branch</td>
                <td class="value">{{ $announcement->branch->name }}</td>
            </tr>
        @endif
        @if($announcement->division)
            <tr>
                <td class="label">Division</td>
                <td class="value">{{ $announcement->division->name }}</td>
            </tr>
        @endif
        @if($announcement->department)
            <tr>
                <td class="label">Department</td>
                <td class="value">{{ $announcement->department->department_name }}</td>
            </tr>
        @endif
        @if($announcement->section)
            <tr>
                <td class="label">Section</td>
                <td class="value">{{ $announcement->section->name }}</td>
            </tr>
        @endif
    </table>

    <div class="content-section">
        {!! $announcement->content !!}
    </div>

    <div class="footer">
        This is an official document generated by the HRMS System. All rights reserved.
    </div>
</body>
</html>
