@extends('structure.master')
@section('content')
    {{-- Search Section --}}
    <div class="row">
        <div class="col-lg-12">
            <div class="card border-0 shadow-sm rounded">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i data-feather="dollar-sign" class="me-2"></i>Search Payroll Process
                    </h5>
                </div>
                <div class="card-header border-bottom p-4">
                    <div class="row align-items-start">
                        {{-- Filter Section --}}
                        <div class="col-md-12">
                            <div class="border rounded shadow-sm p-3 filter-section-bg">
                                <form id="filterForm">
                                    {{-- Keyword Search --}}
                                    <div class="row mb-2">
                                        <div class="col-12">
                                            <label for="keywordSearch" class="form-label text-muted small fw-semibold mb-1">
                                                Keyword Search
                                            </label>
                                            <div class="input-group input-group-md">
                                                <input type="text" class="form-control border-end-0" id="keywordSearch"
                                                    name="keyword"
                                                    placeholder="Search by batch ID, salary month, approval status..."
                                                    aria-label="Keyword Search" value="{{ request('keyword') }}">
                                                <span class="input-group-text border-start-0 input-group-bg">
                                                    <i class="mdi mdi-magnify text-muted"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    {{-- Reset Button --}}
                                    <div class="row">
                                        <div class="col-12 text-end">
                                            <button type="button" id="resetFilters"
                                                class="btn btn-outline-secondary btn-sm">
                                                <i class="mdi mdi-refresh"></i> Reset
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {{-- List Section --}}
        <div class="col-lg-12 mt-3">
            <div class="card border-0 shadow-sm rounded">
                <div class="card-header">
                    <h5 class="card-title mb-0">Payroll Process List</h5>
                </div>
                <div class="card-body">
                    {{-- Action Buttons --}}
                    <div class="d-flex justify-content-between mb-3">
                        <a type="button" class="btn btn-warning btn-sm" href="#">
                            <i style="height: 12px; width: 12px" data-feather="plus"></i> Create New
                        </a>
                    </div>

                    <div class="table-responsive" id="search-result">
                        <table class="table table-bordered table-hover mb-0">
                            <thead class="table-light">
                                <tr>
                                    <th scope="col" class="text-center">#</th>
                                    <th scope="col">Batch ID</th>
                                    <th scope="col">Salary Month</th>
                                    <th scope="col" class="text-center">Approval Status</th>
                                    <th scope="col">Generated By</th>
                                    <th scope="col" class="text-center" style="width: 100px;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                    // Dummy data for demonstration
                                    $payrollProcesses = [
                                        (object) [
                                            'id' => 1,
                                            'batch_id' => 'BATCH-2026-001',
                                            'salary_month' => '2026-01',
                                            'approval_status' => 'Pending',
                                            'generated_by' => 'Admin User',
                                            'company_name' => 'ABC Corporation',
                                            'branch_name' => 'Head Office',
                                            'division_name' => 'IT Division',
                                            'department_name' => 'Development',
                                            'section_name' => 'Backend Team',
                                            'type' => 'Monthly',
                                            'status' => 'Generated',
                                            'approved_by' => null,
                                            'total_amount' => 450000.0,
                                            'total_employee' => 15,
                                            'created_at' => '2026-01-25 10:30:00',
                                        ],
                                        (object) [
                                            'id' => 2,
                                            'batch_id' => 'BATCH-2025-012',
                                            'salary_month' => '2025-12',
                                            'approval_status' => 'Approved',
                                            'generated_by' => 'HR Manager',
                                            'company_name' => 'ABC Corporation',
                                            'branch_name' => 'Regional Office',
                                            'division_name' => 'Sales Division',
                                            'department_name' => 'Marketing',
                                            'section_name' => 'Digital Marketing',
                                            'type' => 'Monthly',
                                            'status' => 'Processed',
                                            'approved_by' => 'Finance Director',
                                            'total_amount' => 380000.0,
                                            'total_employee' => 12,
                                            'created_at' => '2025-12-28 14:20:00',
                                        ],
                                        (object) [
                                            'id' => 3,
                                            'batch_id' => 'BATCH-2025-011',
                                            'salary_month' => '2025-11',
                                            'approval_status' => 'Approved',
                                            'generated_by' => 'Admin User',
                                            'company_name' => 'XYZ Enterprises',
                                            'branch_name' => 'Factory Unit',
                                            'division_name' => 'Production',
                                            'department_name' => 'Manufacturing',
                                            'section_name' => 'Assembly Line',
                                            'type' => 'Monthly',
                                            'status' => 'Processed',
                                            'approved_by' => 'CEO',
                                            'total_amount' => 520000.0,
                                            'total_employee' => 20,
                                            'created_at' => '2025-11-27 09:15:00',
                                        ],
                                        (object) [
                                            'id' => 4,
                                            'batch_id' => 'BATCH-2025-010',
                                            'salary_month' => '2025-10',
                                            'approval_status' => 'Rejected',
                                            'generated_by' => 'HR Officer',
                                            'company_name' => 'ABC Corporation',
                                            'branch_name' => 'Head Office',
                                            'division_name' => 'Admin',
                                            'department_name' => 'Finance',
                                            'section_name' => 'Accounts',
                                            'type' => 'Monthly',
                                            'status' => 'Cancelled',
                                            'approved_by' => null,
                                            'total_amount' => 290000.0,
                                            'total_employee' => 10,
                                            'created_at' => '2025-10-29 16:45:00',
                                        ],
                                        (object) [
                                            'id' => 5,
                                            'batch_id' => 'BATCH-2025-009',
                                            'salary_month' => '2025-09',
                                            'approval_status' => 'Approved',
                                            'generated_by' => 'System Admin',
                                            'company_name' => 'Tech Solutions Ltd',
                                            'branch_name' => 'City Branch',
                                            'division_name' => 'Technology',
                                            'department_name' => 'Software Development',
                                            'section_name' => 'Frontend Team',
                                            'type' => 'Monthly',
                                            'status' => 'Processed',
                                            'approved_by' => 'Finance Manager',
                                            'total_amount' => 610000.0,
                                            'total_employee' => 18,
                                            'created_at' => '2025-09-26 11:30:00',
                                        ],
                                    ];
                                    $sl = 1;
                                @endphp
                                @forelse($payrollProcesses as $item)
                                    <tr>
                                        <th scope="row" class="text-center">{{ $sl++ }}</th>
                                        <td>
                                            <strong class="text-primary">{{ $item->batch_id }}</strong>
                                        </td>
                                        <td>
                                            <i data-feather="calendar" class="text-muted"
                                                style="width: 14px; height: 14px;"></i>
                                            {{ \Carbon\Carbon::parse($item->salary_month)->format('F Y') }}
                                        </td>
                                        <td class="text-center">
                                            @if ($item->approval_status == 'Approved')
                                                <span class="badge text-bg-success">Approved</span>
                                            @elseif($item->approval_status == 'Pending')
                                                <span class="badge text-bg-warning">Pending</span>
                                            @elseif($item->approval_status == 'Rejected')
                                                <span class="badge text-bg-danger">Rejected</span>
                                            @else
                                                <span class="badge text-bg-secondary">{{ $item->approval_status }}</span>
                                            @endif
                                        </td>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <div class="avatar-circle me-2">
                                                    {{ strtoupper(substr($item->generated_by, 0, 2)) }}
                                                </div>
                                                <div>
                                                    <strong>{{ $item->generated_by }}</strong>
                                                </div>
                                            </div>
                                        </td>
                                        <td class="text-center">
                                            <button type="button" class="btn btn-info btn-sm view-details"
                                                data-id="{{ $item->id }}" data-batch-id="{{ $item->batch_id }}"
                                                data-salary-month="{{ \Carbon\Carbon::parse($item->salary_month)->format('F Y') }}"
                                                data-approval-status="{{ $item->approval_status }}"
                                                data-generated-by="{{ $item->generated_by }}"
                                                data-company="{{ $item->company_name }}"
                                                data-branch="{{ $item->branch_name }}"
                                                data-division="{{ $item->division_name }}"
                                                data-department="{{ $item->department_name }}"
                                                data-section="{{ $item->section_name }}" data-type="{{ $item->type }}"
                                                data-status="{{ $item->status }}"
                                                data-approved-by="{{ $item->approved_by ?? 'N/A' }}"
                                                data-total-amount="{{ number_format($item->total_amount, 2) }}"
                                                data-total-employee="{{ $item->total_employee }}"
                                                data-created-at="{{ \Carbon\Carbon::parse($item->created_at)->format('d M, Y H:i A') }}"
                                                title="View Details">
                                                <i style="height: 12px; width: 12px" data-feather="eye"></i>
                                            </button>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="text-center py-4">
                                            <div class="text-muted">
                                                <i data-feather="inbox" style="width: 48px; height: 48px;"></i>
                                                <p class="mt-2 mb-0">No payroll processes found</p>
                                            </div>
                                        </td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                    {{-- Pagination would go here if using real data --}}
                </div>
            </div>
        </div>
    </div>

    {{-- Include Modal --}}
    @include('trial.partials.payroll-process-modal')

    <style>
        .avatar-circle {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 14px;
        }

        .filter-section-bg {
            background-color: #f8f9fa;
        }

        .input-group-bg {
            background-color: #fff;
        }

        .modal-body label.text-muted {
            font-size: 0.875rem;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 0.25rem;
        }
    </style>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function() {
            // Initialize Feather icons
            if (typeof feather !== 'undefined') {
                feather.replace();
            }

            // Handle view details button click
            $('.view-details').on('click', function() {
                // Get data attributes
                const batchId = $(this).data('batch-id');
                const salaryMonth = $(this).data('salary-month');
                const approvalStatus = $(this).data('approval-status');
                const generatedBy = $(this).data('generated-by');
                const company = $(this).data('company');
                const branch = $(this).data('branch');
                const division = $(this).data('division');
                const department = $(this).data('department');
                const section = $(this).data('section');
                const type = $(this).data('type');
                const status = $(this).data('status');
                const approvedBy = $(this).data('approved-by');
                const totalAmount = $(this).data('total-amount');
                const totalEmployee = $(this).data('total-employee');
                const createdAt = $(this).data('created-at');

                // Populate modal
                $('#modal-batch-id').text(batchId);
                $('#modal-salary-month').text(salaryMonth);
                $('#modal-type').text(type);
                $('#modal-status').html('<span class="badge text-bg-info">' + status + '</span>');
                $('#modal-company').text(company);
                $('#modal-branch').text(branch);
                $('#modal-division').text(division);
                $('#modal-department').text(department);
                $('#modal-section').text(section);
                $('#modal-generated-by').text(generatedBy);
                $('#modal-approved-by').text(approvedBy);
                $('#modal-total-amount').text('৳ ' + totalAmount);
                $('#modal-total-employee').text(totalEmployee);
                $('#modal-created-at').text(createdAt);

                // Set approval status with badge
                let approvalBadge = '';
                if (approvalStatus === 'Approved') {
                    approvalBadge = '<span class="badge text-bg-success">Approved</span>';
                } else if (approvalStatus === 'Pending') {
                    approvalBadge = '<span class="badge text-bg-warning">Pending</span>';
                } else if (approvalStatus === 'Rejected') {
                    approvalBadge = '<span class="badge text-bg-danger">Rejected</span>';
                } else {
                    approvalBadge = '<span class="badge text-bg-secondary">' + approvalStatus + '</span>';
                }
                $('#modal-approval-status').html(approvalBadge);

                // Show modal
                const modal = new bootstrap.Modal(document.getElementById('viewDetailsModal'));
                modal.show();

                // Re-initialize feather icons in modal
                setTimeout(function() {
                    if (typeof feather !== 'undefined') {
                        feather.replace();
                    }
                }, 100);
            });

            // Function to perform AJAX search (for future implementation)
            function fetchData(url = window.location.href) {
                const queryString = $('#filterForm').serialize();

                $.ajax({
                    url: url,
                    method: "GET",
                    data: queryString,
                    beforeSend: function() {
                        $('#search-result').html(
                            '<div class="text-center py-4 text-muted">Loading Data...</div>');
                    },
                    success: function(response) {
                        $('#search-result').html(response);
                        // Reinitialize Feather icons
                        if (typeof feather !== 'undefined') {
                            feather.replace();
                        }
                        // Re-bind event handlers
                        bindViewDetailsHandlers();
                    },
                    error: function(xhr) {
                        console.error('AJAX Error:', xhr.responseText);
                        $('#search-result').html(
                            '<div class="text-center py-4 text-danger">Error loading data</div>');
                    }
                });
            }

            // Bind view details handlers (for AJAX-loaded content)
            function bindViewDetailsHandlers() {
                $('.view-details').off('click').on('click', function() {
                    // Same logic as above
                    const batchId = $(this).data('batch-id');
                    const salaryMonth = $(this).data('salary-month');
                    const approvalStatus = $(this).data('approval-status');
                    const generatedBy = $(this).data('generated-by');
                    const company = $(this).data('company');
                    const branch = $(this).data('branch');
                    const division = $(this).data('division');
                    const department = $(this).data('department');
                    const section = $(this).data('section');
                    const type = $(this).data('type');
                    const status = $(this).data('status');
                    const approvedBy = $(this).data('approved-by');
                    const totalAmount = $(this).data('total-amount');
                    const totalEmployee = $(this).data('total-employee');
                    const createdAt = $(this).data('created-at');

                    $('#modal-batch-id').text(batchId);
                    $('#modal-salary-month').text(salaryMonth);
                    $('#modal-type').text(type);
                    $('#modal-status').html('<span class="badge text-bg-info">' + status + '</span>');
                    $('#modal-company').text(company);
                    $('#modal-branch').text(branch);
                    $('#modal-division').text(division);
                    $('#modal-department').text(department);
                    $('#modal-section').text(section);
                    $('#modal-generated-by').text(generatedBy);
                    $('#modal-approved-by').text(approvedBy);
                    $('#modal-total-amount').text('৳ ' + totalAmount);
                    $('#modal-total-employee').text(totalEmployee);
                    $('#modal-created-at').text(createdAt);

                    let approvalBadge = '';
                    if (approvalStatus === 'Approved') {
                        approvalBadge = '<span class="badge text-bg-success">Approved</span>';
                    } else if (approvalStatus === 'Pending') {
                        approvalBadge = '<span class="badge text-bg-warning">Pending</span>';
                    } else if (approvalStatus === 'Rejected') {
                        approvalBadge = '<span class="badge text-bg-danger">Rejected</span>';
                    } else {
                        approvalBadge = '<span class="badge text-bg-secondary">' + approvalStatus +
                            '</span>';
                    }
                    $('#modal-approval-status').html(approvalBadge);

                    const modal = new bootstrap.Modal(document.getElementById('viewDetailsModal'));
                    modal.show();

                    setTimeout(function() {
                        if (typeof feather !== 'undefined') {
                            feather.replace();
                        }
                    }, 100);
                });
            }

            // Trigger search on input or change (for future implementation)
            $('#filterForm').on('input change', function(e) {
                e.preventDefault();
                // fetchData(); // Uncomment when backend is ready
            });

            // Reset filters
            $('#resetFilters').on('click', function() {
                $('#filterForm')[0].reset();
                // fetchData(); // Uncomment when backend is ready
            });

            // Handle pagination clicks (for future implementation)
            $(document).on('click', '.pagination a', function(e) {
                e.preventDefault();
                const url = $(this).attr('href');
                if (url) {
                    // fetchData(url); // Uncomment when backend is ready
                }
            });
        });
    </script>
@endsection
