{{-- View Details Modal --}}
<div class="modal fade" id="viewDetailsModal" tabindex="-1" aria-labelledby="viewDetailsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header bg-primary text-white">
                <h5 class="modal-title" id="viewDetailsModalLabel">
                    <i data-feather="info" class="me-2"></i>Payroll Process Details
                </h5>

                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    {{-- Basic Information --}}
                    <div class="col-12 mb-4">
                        <h6 class="text-primary border-bottom pb-2 mb-3">
                            <i data-feather="file-text" class="me-2" style="width: 16px; height: 16px;"></i>
                            Basic Information
                        </h6>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Batch ID</label>
                                <p class="fw-bold mb-0" id="modal-batch-id">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Salary Month</label>
                                <p class="fw-bold mb-0" id="modal-salary-month">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Type</label>
                                <p class="fw-bold mb-0" id="modal-type">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Status</label>
                                <p class="fw-bold mb-0" id="modal-status">-</p>
                            </div>
                        </div>
                    </div>

                    {{-- Organization Information --}}
                    <div class="col-12 mb-4">
                        <h6 class="text-primary border-bottom pb-2 mb-3">
                            <i data-feather="briefcase" class="me-2" style="width: 16px; height: 16px;"></i>
                            Organization Details
                        </h6>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Company</label>
                                <p class="fw-bold mb-0" id="modal-company">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Branch</label>
                                <p class="fw-bold mb-0" id="modal-branch">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Division</label>
                                <p class="fw-bold mb-0" id="modal-division">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Department</label>
                                <p class="fw-bold mb-0" id="modal-department">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Section</label>
                                <p class="fw-bold mb-0" id="modal-section">-</p>
                            </div>
                        </div>
                    </div>

                    {{-- Approval Information --}}
                    <div class="col-12 mb-4">
                        <h6 class="text-primary border-bottom pb-2 mb-3">
                            <i data-feather="check-circle" class="me-2" style="width: 16px; height: 16px;"></i>
                            Approval & Processing
                        </h6>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Approval Status</label>
                                <p class="fw-bold mb-0" id="modal-approval-status">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Generated By</label>
                                <p class="fw-bold mb-0" id="modal-generated-by">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Approved By</label>
                                <p class="fw-bold mb-0" id="modal-approved-by">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Created At</label>
                                <p class="fw-bold mb-0" id="modal-created-at">-</p>
                            </div>
                        </div>
                    </div>

                    {{-- Financial Summary --}}
                    <div class="col-12">
                        <h6 class="text-primary border-bottom pb-2 mb-3">
                            <i data-feather="dollar-sign" class="me-2" style="width: 16px; height: 16px;"></i>
                            Financial Summary
                        </h6>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Total Employees</label>
                                <p class="fw-bold mb-0 fs-5 text-info" id="modal-total-employee">-</p>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label class="text-muted small">Total Amount</label>
                                <p class="fw-bold mb-0 fs-5 text-success" id="modal-total-amount">-</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a href="#" id="view-eligible-btn" class="btn btn-primary">
                    <i data-feather="users" class="me-1"></i>
                    View Eligible Employees
                </a>

                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    Close
                </button>
            </div>

        </div>
    </div>
</div>
