@extends('structure.master')
@section('content')
    {{-- Search Section --}}
    <div class="row">
        <div class="col-lg-12">
            @can('salary.view')
            <div class="card border-0 shadow-sm rounded">
                <div class="card-header">
                    <h5 class="card-title mb-0">
                        <i data-feather="dollar-sign" class="me-2"></i>Search Payroll Process Batch
                    </h5>
                </div>
                <div class="card-header border-bottom p-4">
                    <div class="row align-items-start">
                        {{-- Filter Section --}}
                        <div class="col-md-12">
                            <div class="border rounded shadow-sm p-3 filter-section-bg">

                                <form id="filterForm">
                                    {{-- First Row: Keyword Search --}}
                                    <div class="row mb-2">
                                        <div class="col-12">
                                            <label for="keywordSearch" class="form-label text-muted small fw-semibold mb-1">
                                                Keyword Search
                                            </label>
                                            <div class="input-group input-group-md">
                                                <input type="text" class="form-control border-end-0" id="keywordSearch"
                                                       name="keyword" placeholder="Search by batch id, generated by"
                                                       aria-label="Keyword Search" value="{{ request('keyword') }}">
                                                <span class="input-group-text border-start-0 input-group-bg">
                                                    <i class="mdi mdi-magnify text-muted"></i>
                                                </span>
                                            </div>
                                        </div>
                                    </div>

                                    {{-- Second Row: Employee, Increment Method, Status --}}
                                    <div class="row mb-2">

                                        <div class="col-md-3">
                                            <label for="salaryMonth" class="form-label text-muted small fw-semibold mb-1">
                                                Salary Month
                                            </label>
                                            <input type="month" class="form-control form-control-sm" id="salaryMonth"
                                                   name="salary_month" value="{{ request('salary_month') }}">
                                        </div>

                                        <div class="col-md-3">
                                            <label for="effectiveFrom" class="form-label text-muted small fw-semibold mb-1">
                                                Generated at (Start)
                                            </label>
                                            <input type="date" class="form-control form-control-sm" id="effectiveFrom"
                                                   name="from_start" value="{{ request('from_start') }}">
                                        </div>
                                        <div class="col-md-3">
                                            <label for="effectiveTo" class="form-label text-muted small fw-semibold mb-1">
                                                Generated at (End)
                                            </label>
                                            <input type="date" class="form-control form-control-sm" id="effectiveTo"
                                                   name="from_end" value="{{ request('from_end') }}">
                                        </div>
                                        <div class="col-md-3">
                                            <label for="statusFilter" class="form-label text-muted small fw-semibold mb-1">
                                                Status
                                            </label>
                                            <select class="form-select form-select-sm" id="statusFilter" name="status">
                                                <option value="">All Status</option>
                                                <option value="pending"
                                                    {{ request('status') == 'pending' ? 'selected' : '' }}>Pending</option>
                                                <option value="approved"
                                                    {{ request('status') == 'approved' ? 'selected' : '' }}>Approved
                                                </option>
                                                <option value="rejected"
                                                    {{ request('status') == 'rejected' ? 'selected' : '' }}>Rejected
                                                </option>
                                            </select>
                                        </div>


                                    </div>

                                    {{-- Reset Button --}}
                                    <div class="row">
                                        <div class="col-12 text-end">
                                            <button type="button" id="resetFilters"
                                                    class="btn btn-outline-secondary btn-sm">
                                                <i class="mdi mdi-refresh"></i> Reset
                                            </button>
                                        </div>
                                    </div>
                                </form>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @endcan
        </div>

        {{-- List Section --}}
        <div class="col-lg-12 mt-3">
            <div class="card border-0 shadow-sm rounded">
                <div class="card-header">
                    <h5 class="card-title mb-0">Salary Process List</h5>
                </div>
                <div class="card-body">
                    {{-- Action Buttons --}}
                    <div class="d-flex justify-content-between mb-3">
                        @can('salary.create')
                        <a type="button" class="btn btn-warning btn-sm" href="{{route('salary.create')}}">
                            <i style="height: 12px; width: 12px" data-feather="plus"></i> Create
                        </a>
                        @else
                        <div></div>
                        @endcan
                        <div class="d-flex gap-2">
                            <button type="button" id="exportExcelBtn" class="btn btn-success btn-sm no-loader">
                                <i class="bi bi-file-earmark-excel me-1"></i> Export
                            </button>
                            <button type="button" id="printBtn" class="btn btn-secondary btn-sm no-loader">
                                <i class="bi bi-printer me-1"></i> Print
                            </button>
                        </div>
                    </div>

                    <div class="table-responsive" id="search-result">
                        @include('payroll.salary.partials.search_results')
                    </div>

                    <div class="mt-2">
                        {{ $payrollProcesses->links() }}
                    </div>

                </div>
            </div>
        </div>
    </div>

    {{-- Include Modal --}}
    @include('payroll.salary.partials.view')

    <style>
        .avatar-circle {
            width: 36px;
            height: 36px;
            border-radius: 50%;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 14px;
        }

        .filter-section-bg {
            background-color: #f8f9fa;
        }

        .input-group-bg {
            background-color: #fff;
        }

        .modal-body label.text-muted {
            font-size: 0.875rem;
            font-weight: 500;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            margin-bottom: 0.25rem;
        }
    </style>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function() {
            // Function to perform AJAX search
            function fetchData(url = "{{ route('salary.index') }}") {
                const queryString = $('#filterForm').serialize();

                $.ajax({
                    url: url,
                    method: "GET",
                    data: queryString,
                    beforeSend: function() {
                        $('#search-result').html(
                            '<div class="text-center py-4 text-muted">Loading Data...</div>');
                    },
                    success: function(response) {
                        $('#search-result').html(response);
                        // Reinitialize Feather icons if used in results
                        if (typeof feather !== 'undefined') {
                            feather.replace();
                        }
                        // Update URL without page param
                        const newUrl = '?' + queryString;
                        window.history.pushState(null, '', newUrl || location.pathname);
                    },
                    error: function(xhr) {
                        console.error('AJAX Error:', xhr.responseText);
                    }
                });
            }

            // Trigger search on input or change
            $('#filterForm').on('input change', function(e) {
                e.preventDefault();
                fetchData();
            });

            // Reset filters: clear form and reload base URL
            $('#resetFilters').on('click', function() {
                $('#filterForm')[0].reset();
                $('.select2_list').val(null).trigger('change');
                fetchData();
            });

            // Handle pagination links via AJAX
            $(document).on('click', '.pagination a', function(e) {
                e.preventDefault();
                const url = $(this).attr('href');
                if (url) {
                    fetchData(url);
                }
            });

            // Excel Export
            $('#exportExcelBtn').on('click', function(e) {
                e.preventDefault();
                window.ignoreBeforeUnload = true;
                setTimeout(() => { window.ignoreBeforeUnload = false; }, 2000);
                
                const queryString = $('#filterForm').serialize();
                window.location.href = "{{ route('salary.export.excel') }}?" + queryString;
            });

            // Print
            $('#printBtn').on('click', function(e) {
                e.preventDefault();
                const queryString = $('#filterForm').serialize();
                window.open("{{ route('salary.print') }}?" + queryString, '_blank');
            });
        });
    </script>
    <script>
        $(document).ready(function() {
            // Initialize Feather icons
            if (typeof feather !== 'undefined') {
                feather.replace();
            }

            /* ================= VIEW DETAILS CLICK ================= */

            $('.view-details').on('click', function() {

                const payrollId = $(this).data('id'); // ✅ REQUIRED

                const batchId = $(this).data('batch-id');
                const salaryMonth = $(this).data('salary-month');
                const approvalStatus = $(this).data('approval-status');
                const generatedBy = $(this).data('generated-by');
                const company = $(this).data('company');
                const branch = $(this).data('branch');
                const division = $(this).data('division');
                const department = $(this).data('department');
                const section = $(this).data('section');
                const type = $(this).data('type');
                const status = $(this).data('status');
                const approvedBy = $(this).data('approved-by');
                const totalAmount = $(this).data('total-amount');
                const totalEmployee = $(this).data('total-employee');
                const createdAt = $(this).data('created-at');

                /* ================= SET MODAL DATA ================= */

                $('#modal-batch-id').text(batchId);
                $('#modal-salary-month').text(salaryMonth);
                $('#modal-type').text(type);
                $('#modal-company').text(company);
                $('#modal-branch').text(branch);
                $('#modal-division').text(division);
                $('#modal-department').text(department);
                $('#modal-section').text(section);
                $('#modal-generated-by').text(generatedBy);
                $('#modal-approved-by').text(approvedBy);
                $('#modal-total-amount').text('৳ ' + totalAmount);
                $('#modal-total-employee').text(totalEmployee);
                $('#modal-created-at').text(createdAt);

                /* ================= APPROVAL BADGE ================= */

                let approvalBadge = '';
                if (approvalStatus === 'Approved') {
                    approvalBadge = '<span class="badge text-bg-success">Approved</span>';
                } else if (approvalStatus === 'Pending') {
                    approvalBadge = '<span class="badge text-bg-warning">Pending</span>';
                } else if (approvalStatus === 'Rejected') {
                    approvalBadge = '<span class="badge text-bg-danger">Rejected</span>';
                } else {
                    approvalBadge = '<span class="badge text-bg-secondary">' + approvalStatus + '</span>';
                }
                $('#modal-approval-status').html(approvalBadge);

                /* ================= SET VIEW ELIGIBLE BUTTON ================= */

                const viewUrl = "{{ route('salary.show', ':id') }}".replace(':id', payrollId);
                $('#view-eligible-btn').attr('href', viewUrl);

                /* ================= SHOW MODAL ================= */

                const modal = new bootstrap.Modal(document.getElementById('viewDetailsModal'));
                modal.show();

                setTimeout(function() {
                    if (typeof feather !== 'undefined') {
                        feather.replace();
                    }
                }, 100);
            });

            /* ================= AJAX SUPPORT ================= */

            function bindViewDetailsHandlers() {
                $('.view-details').off('click').on('click', function() {

                    const payrollId = $(this).data('id'); // ✅ REQUIRED

                    const batchId = $(this).data('batch-id');
                    const salaryMonth = $(this).data('salary-month');
                    const approvalStatus = $(this).data('approval-status');
                    const generatedBy = $(this).data('generated-by');
                    const company = $(this).data('company');
                    const branch = $(this).data('branch');
                    const division = $(this).data('division');
                    const department = $(this).data('department');
                    const section = $(this).data('section');
                    const type = $(this).data('type');
                    const approvedBy = $(this).data('approved-by');
                    const totalAmount = $(this).data('total-amount');
                    const totalEmployee = $(this).data('total-employee');
                    const createdAt = $(this).data('created-at');

                    $('#modal-batch-id').text(batchId);
                    $('#modal-salary-month').text(salaryMonth);
                    $('#modal-type').text(type);
                    $('#modal-company').text(company);
                    $('#modal-branch').text(branch);
                    $('#modal-division').text(division);
                    $('#modal-department').text(department);
                    $('#modal-section').text(section);
                    $('#modal-generated-by').text(generatedBy);
                    $('#modal-approved-by').text(approvedBy);
                    $('#modal-total-amount').text('৳ ' + totalAmount);
                    $('#modal-total-employee').text(totalEmployee);
                    $('#modal-created-at').text(createdAt);

                    let approvalBadge = '';
                    if (approvalStatus === 'Approved') {
                        approvalBadge = '<span class="badge text-bg-success">Approved</span>';
                    } else if (approvalStatus === 'Pending') {
                        approvalBadge = '<span class="badge text-bg-warning">Pending</span>';
                    } else if (approvalStatus === 'Rejected') {
                        approvalBadge = '<span class="badge text-bg-danger">Rejected</span>';
                    } else {
                        approvalBadge = '<span class="badge text-bg-secondary">' + approvalStatus + '</span>';
                    }
                    $('#modal-approval-status').html(approvalBadge);

                    /* ================= SET VIEW ELIGIBLE BUTTON ================= */

                    const viewUrl = "{{ route('salary.show', ':id') }}".replace(':id', payrollId);
                    $('#view-eligible-btn').attr('href', viewUrl);

                    const modal = new bootstrap.Modal(document.getElementById('viewDetailsModal'));
                    modal.show();

                    setTimeout(function() {
                        if (typeof feather !== 'undefined') {
                            feather.replace();
                        }
                    }, 100);
                });
            }

        });
    </script>


@endsection

