<?php

namespace App\Exports\Payroll;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Carbon\Carbon;

class SalaryProcessExport implements FromCollection, WithHeadings, WithMapping
{
    protected $records;

    public function __construct($records)
    {
        $this->records = $records;
    }

    public function collection()
    {
        return $this->records;
    }

    public function headings(): array
    {
        return [
            '#',
            'Batch ID',
            'Salary Month',
            'Total Employees',
            'Total Amount',
            'Generated At',
            'Generated By',
            'Approval Status',
        ];
    }

    public function map($row): array
    {
        static $index = 0;
        $index++;

        return [
            $index,
            $row->batch_id ?? 'N/A',
            $row->salary_month ? Carbon::parse($row->salary_month)->format('F Y') : '—',
            $row->total_employee ?? 0,
            $row->total_amount ?? '0.00',
            $row->created_at ? Carbon::parse($row->created_at)->format('d M Y') : '—',
            $row->generatedBy?->employee?->full_name ?? $row->generatedBy?->name ?? 'N/A',
            ucfirst($row->approval_status ?? 'Pending'),
        ];
    }
}
